### ISSUE TITLE
Workers become "Offline" on Elastic k8s clusters during scale down process.

### ISSUE THREAD

**Issue by theobolo** [evryfs/github-actions-runner-operator#110]
Hello, i'm posting this issue since i'm using your projet in Production to run all our actions pipelines.
I'm using your operator like this :

Having a kubernetes cluster, with 2 nodeGroups :

 - a `controller-nodegroup` with one m5.large instance, that runs the github-actions-controller, no autoscaler
 - a `worker-nodegroup` with as many m5.xlarge instance as needed managed by a cluster-autoscaler / resources-limits / nodeAffinity rules

My goal is to ensure that each new Actions Jobs (runners), are scheduled on a fresh k8s "node" : 1 pod runner = 1 m5.xlarge 
This is working very well, each new runner spins up a new node on my nodegroup, based on resourcesLimits and nodeAffinity rules. If pipelines are not used then the operator scales down runners and cluster-autoscaler do the same after few minutes for the unused nodes.

Problems are coming during the scale down process : 

After a typical day of running pipelines, github is reporting "Offline" workers, and the github-actions-runner-controller stay stuck into "API Not in Sync" state. 

It seems that some workers are not removed correctly : 

![Screenshot_20201016-212107_Chrome.jpg](https://user-images.githubusercontent.com/7281773/96300463-d7fcb880-0ff5-11eb-93b4-18758e525761.jpg)

![Screenshot_20201016-212130_Termux.jpg](https://user-images.githubusercontent.com/7281773/96300468-da5f1280-0ff5-11eb-9282-6cd0dc531ada.jpg)

![Screenshot_20201016-212221_Termux.jpg](https://user-images.githubusercontent.com/7281773/96300473-dcc16c80-0ff5-11eb-85cc-77816840bffc.jpg)

And the runner CRD definition : 

```
apiVersion: garo.tietoevry.com/v1alpha1
kind: GithubActionRunner
metadata:
  name: runner-pool
  namespace: github-actions-runner
spec:
  minRunners: 1
  maxRunners: 20
  organization: go-aos
  reconciliationPeriod: 5s
  tokenRef:
    key: GH_TOKEN
    name: actions-runner-secret
  podTemplateSpec:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "3903"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - actions-runner
      containers:
        - name: runner
          image: quay.io/evryfs/github-actions-runner:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /remove_runner.sh
          resources:
            limits:
              cpu: "4"
              memory: "14Gi"
            requests:
              cpu: "2"
              memory: "6Gi"
          env:
            - name: RUNNER_DEBUG
              value: "true"
            - name: DOCKER_TLS_CERTDIR
              value: /certs
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: GH_ORG
              value: go-aos
            - name: TZ
              value: Europe/Paris
          envFrom:
            - secretRef:
                name: actions-runner-secret
          volumeMounts:
            - mountPath: /certs
              name: docker-certs
            - mountPath: /home/runner/_diag
              name: runner-diag
            - mountPath: /home/runner/_work
              name: runner-work
            - mountPath: /home/runner/.m2
              name: mvn-repo
        - name: docker
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          image: docker:stable-dind
          imagePullPolicy: Always
          args:
            # See linked issues from: https://github.com/evryfs/github-actions-runner-operator/issues/39
            - --mtu=1430
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-storage
            - mountPath: /certs
              name: docker-certs
            - mountPath: /home/runner/_work
              name: runner-work
        - name: exporter
          image: quay.io/evryfs/github-actions-runner-metrics:v0.0.3
          ports:
            - containerPort: 3903
              protocol: TCP
          volumeMounts:
            - name: runner-diag
              mountPath: /_diag
              readOnly: true
      volumes:
        - emptyDir:
            medium: Memory
          name: runner-work
        - emptyDir: {}
          name: runner-diag
        - emptyDir: {}
          name: mvn-repo
        - emptyDir: {}
          name: docker-storage
        - emptyDir: {}
          name: docker-certs

```
I'm also adding my HelmRelease yaml, since i'm using a Gitops approch on my cluster : 

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: github-actions-runner-operator
  namespace: github-actions-runner
spec:
  forceUpgrade: true
  releaseName: github-actions-runner-operator
  chart:
    git: git@github.com:evryfs/helm-charts.git
    path: charts/github-actions-runner-operator
    ref: master
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: role
              operator: In
              values:
              - controller-runner
```

Did you already face the same behaviour ?
Cheers
