### ISSUE TITLE
GithubActionRunner: error: no installation found for ORG

### ISSUE THREAD

**Issue by dennybaa** [evryfs/github-actions-runner-operator#185]
Hello, could you please share details what might be missing
```
      apiVersion: garo.tietoevry.com/v1alpha1
      kind: GithubActionRunner
      metadata:
        name: github-actions-deployer-pool
      spec:
        minRunners: 2
        maxRunners: 6
        organization: ORG
        reconciliationPeriod: 1m
        repository: foo/bar
...
```
