### ISSUE TITLE
Metadata labels not accepted

### ISSUE THREAD

**Issue by jarojasm95** [evryfs/github-actions-runner-operator#344]
Using the following manifest to create a runner pool

```yaml
apiVersion: garo.tietoevry.com/v1alpha1
kind: GithubActionRunner
metadata:
  name: my-runner-pool
spec:
  # minimum running pods, required
  minRunners: 1
  # max number of pods, required
  maxRunners: 6
  # the github org, required
  organization: jarojasm95
  # How often it will reconcile, optional, default 1m
  reconciliationPeriod: 1m
  # if runner for repo, optional
  # repository: "theRepoName"
  podTemplateSpec:
    metadata:
      labels:
        project: github-runner
    spec:
...
```

And the resulting pod does not contain the "project" label, the `GithubActionRunner/my-runner-pool` is also mutated to:
```yaml
podTemplateSpec:
  metadata: {}
```
