### ISSUE TITLE
Can't run Jobs with JS & Docker Actions if they are interdependent

### ISSUE THREAD

**Issue by zackijack** [evryfs/github-actions-runner-operator#39]
If in my workflow, there are 2 types of Actions:

- Javascript (which run directly on the `runner` pod, e.g. `actions/checkout@v2`)
- Docker (which run using DinD on the `docker` pod, e.g. `docker/build-push-action@v1.1.0`)

And if these 2 Actions are interdependent, then I will get an error.

For example, the workflow that I have is more or less like this:

```yaml
name: Build and push Docker image

on:
  push:
    branches:
      - master

jobs:
  build-push:
    name: build-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: your-repo/your-image
          tags: latest
```

the `docker/build-push-action@v1.1.0` will fail because it cannot find the Dockerfiles that have been cloned by `actions/checkout@v2`. This error does not occur if using the hosted runner.

does this happen because of the `runner` and `docker` run in different containers? I use the manifest from the example [here](https://github.com/evryfs/github-actions-runner-operator/blob/master/deploy/crds/garo.tietoevry.com_v1alpha1_githubactionrunner_cr.yaml).

Is there a solution to this problem?
