### ISSUE TITLE
After a couple of hours of not using the runner, it will become offline

### ISSUE THREAD

**Issue by ni-aackerman** [evryfs/github-actions-runner-operator#556]
So after everything is up an running, did run some jobs, all is good but then, after not using the runner for some hours, it wil become offline, and I will have to delete the runner pool and delete the runner from github so that it gets recreated. Is there some setting like idle timeout or something like that? I do have the minimum runner set to 1 in my CRD

**Comment by ni-aackerman** [comment]
Hello?

**Comment by davidkarlsen** [comment]
What does the logs of the pod say? I am no longer working with tietoevry, and no longer have write-access to the repo - but might be able to shed some light on what is wrong.

**Comment by ni-skopp** [comment]
Hi @davidkarlsen 

we have these in our logs of the pod

```
# Runner removal

Cannot connect to server, because config files are missing. Skipping removing runner from the server.
Does not exist. Skipping Removing .credentials
Does not exist. Skipping Removing .runner


--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication


√ Connected to GitHub

# Runner Registration




A runner exists with the same name
A runner exists with the same name runner-pool-pod-s4jd2.
```
looks like it can't be removed which cause it crashloop since the same pod is already running, do know where to look why it's failing to  do so? 

> Cannot connect to server, because config files are missing.

**Comment by davidkarlsen** [comment]
BTW: Love traktor ;-)

**Comment by ni-skopp** [comment]
I think this is the problem that we need to always force-remove it and sometimes recreate the runner-pool, I've added `restartPolicy: Never` , lets see if it's help

```
apiVersion: garo.tietoevry.com/v1alpha1
kind: GithubActionRunner
metadata:
  name: runner-pool
  namespace: github-actions-runner-operator
spec:
  minRunners: 1
  maxRunners: 9
  reconciliationPeriod: 1m
  podTemplateSpec:
    metadata:
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "3903"
    spec:
      restartPolicy: Never
      affinity:
```
