### ISSUE TITLE
Negative CURRENTPOOLSIZE for GithubActionRunner

### ISSUE THREAD

**Issue by andypanix** [evryfs/github-actions-runner-operator#85]
Hi @davidkarlsen,

I've noticed a strange behavior. After running some jobs and after seeing the runner pool pods correctly scaling up and down, the runner pool pods scaled to 0. Inspecting the cluster this is what I saw:

```
> kubectl get po
NAME                                              READY   STATUS    RESTARTS   AGE
github-actions-runner-operator-5b99949466-tgnhh   1/1     Running   0          54m
> kubectl get GithubActionRunner/runner-pool
NAME          CURRENTPOOLSIZE
runner-pool   -517
```

Besides, on GitHub "Self-hosted runners" config pane I see two (non-existant) offline runners:

![image](https://user-images.githubusercontent.com/100491/90631131-7b159980-e222-11ea-8bc7-5d75f89b6d9a.png)

I'm using version v2.2.0 of github-actions-runner-operator chart.

Testing again (with a new clean installation of the operator and the runner), I was able to replicate the problem that seems related to the termination of the runner pod:

```
> k get po && k get GithubActionRunner/runner-pool
NAME                                              READY   STATUS    RESTARTS   AGE
github-actions-runner-operator-775997cd8c-sl6h6   1/1     Running   0          26m
runner-pool-pod-44l6p                             2/2     Running   0          19m
runner-pool-pod-dr56b                             2/2     Running   0          16m
runner-pool-pod-dx7c4                             2/2     Running   0          21m
runner-pool-pod-glxrt                             2/2     Running   1          7m37s
runner-pool-pod-lhjxv                             2/2     Running   0          25m
runner-pool-pod-n8ggf                             2/2     Running   1          10m
runner-pool-pod-s6qkn                             2/2     Running   0          18m
runner-pool-pod-szfkq                             2/2     Running   0          20m
runner-pool-pod-wqmcb                             2/2     Running   0          4m36s
NAME          CURRENTPOOLSIZE
runner-pool   9

 ~/www/github/actions-runner .............................................................................................. spark-op-services/saas-github kube | 14:18:18
> k get po && k get GithubActionRunner/runner-pool
NAME                                              READY   STATUS    RESTARTS   AGE
github-actions-runner-operator-775997cd8c-sl6h6   1/1     Running   0          29m
runner-pool-pod-44l6p                             2/2     Running   0          23m
runner-pool-pod-dr56b                             2/2     Running   0          20m
runner-pool-pod-dx7c4                             2/2     Running   0          25m
runner-pool-pod-glxrt                             2/2     Running   1          11m
runner-pool-pod-lhjxv                             2/2     Running   0          29m
runner-pool-pod-n8ggf                             2/2     Running   1          14m
runner-pool-pod-szfkq                             2/2     Running   0          24m
NAME          CURRENTPOOLSIZE
runner-pool   -180

 ~/www/github/actions-runner .............................................................................................. spark-op-services/saas-github kube | 14:21:49
> k get po && k get GithubActionRunner/runner-pool
NAME                                              READY   STATUS        RESTARTS   AGE
github-actions-runner-operator-775997cd8c-sl6h6   1/1     Running       0          34m
runner-pool-pod-44l6p                             2/2     Running       0          28m
runner-pool-pod-dr56b                             2/2     Running       0          25m
runner-pool-pod-dx7c4                             2/2     Running       0          30m
runner-pool-pod-glxrt                             2/2     Running       1          16m
runner-pool-pod-lhjxv                             2/2     Running       0          34m
runner-pool-pod-n8ggf                             2/2     Terminating   1          19m
runner-pool-pod-szfkq                             2/2     Running       0          29m
NAME          CURRENTPOOLSIZE
runner-pool   -217
```

And here some interesting events:

```
> kubectl get events
15m         Normal    Pulling             pod/runner-pool-pod-wqmcb                              Pulling image "sparkfabrik/github-actions-runner:latest"
15m         Normal    Pulled              pod/runner-pool-pod-wqmcb                              Successfully pulled image "sparkfabrik/github-actions-runner:latest"
15m         Normal    Created             pod/runner-pool-pod-wqmcb                              Created container runner
15m         Normal    Pulling             pod/runner-pool-pod-wqmcb                              Pulling image "docker:stable-dind"
15m         Normal    Started             pod/runner-pool-pod-wqmcb                              Started container runner
15m         Normal    Pulled              pod/runner-pool-pod-wqmcb                              Successfully pulled image "docker:stable-dind"
15m         Normal    Created             pod/runner-pool-pod-wqmcb                              Created container docker
15m         Normal    Started             pod/runner-pool-pod-wqmcb                              Started container docker
9m32s       Normal    Killing             pod/runner-pool-pod-s6qkn                              Stopping container docker
2m30s       Normal    Scaling             githubactionrunner/runner-pool                         (combined from similar events): Deleted pod saas-github/runner-pool-pod-n8ggf
9m32s       Normal    Killing             pod/runner-pool-pod-s6qkn                              Stopping container runner
9m31s       Normal    Killing             pod/runner-pool-pod-wqmcb                              Stopping container docker
9m31s       Normal    Killing             pod/runner-pool-pod-wqmcb                              Stopping container runner
9m27s       Normal    Scaling             githubactionrunner/runner-pool                         Deleted pod saas-github/runner-pool-pod-wqmcb
9m27s       Normal    Scaling             githubactionrunner/runner-pool                         Deleted pod saas-github/runner-pool-pod-s6qkn
8m59s       Warning   FailedPreStopHook   pod/runner-pool-pod-s6qkn                              Exec lifecycle hook ([/bin/bash -c /remove_runner.sh]) for Container "runner" in Pod "runner-pool-pod-s6qkn_saas-github(742ecdfe-e213-11ea-8e34-42010a8400d1)" failed - error: command '/bin/bash -c /remove_runner.sh' exited with 137: , message: "\n# Runner removal\n\n"
8m58s       Warning   FailedPreStopHook   pod/runner-pool-pod-wqmcb                              Exec lifecycle hook ([/bin/bash -c /remove_runner.sh]) for Container "runner" in Pod "runner-pool-pod-wqmcb_saas-github(6c08a1c6-e215-11ea-8e34-42010a8400d1)" failed - error: command '/bin/bash -c /remove_runner.sh' exited with 137: , message: "\n# Runner removal\n\n"
2m30s       Normal    Killing             pod/runner-pool-pod-n8ggf                              Stopping container docker
2m30s       Normal    Killing             pod/runner-pool-pod-n8ggf                              Stopping container runner
115s        Normal    Killing             pod/runner-pool-pod-dx7c4                              Stopping container docker
115s        Normal    Killing             pod/runner-pool-pod-dx7c4                              Stopping container runner
100s        Normal    Scaling             githubactionrunner/runner-pool                         Deleted pod saas-github/runner-pool-pod-dx7c4
```

Thanks!

**Comment by davidkarlsen** [comment]
Make sure you configure the pods like https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L55 and https://github.com/evryfs/github-actions-runner-operator/blob/master/config/samples/garo_v1alpha1_githubactionrunner.yaml#L66 so that they are able to unregister cleanly.

**Comment by andypanix** [comment]
This is my runner manifest. It seems fine 🤔 

```
apiVersion: garo.tietoevry.com/v1alpha1
kind: GithubActionRunner
metadata:
  name: runner-pool
spec:
  # minimum running pods
  minRunners: 1
  # max number of pods
  maxRunners: 30
  organization: sparkfabrik
  # How often it will reconcile
  reconciliationPeriod: 1m
  # if runner for repo
  # repository: "theRepoName"
  tokenRef:
    key: GH_TOKEN
    name: actions-runner
  podTemplateSpec:
    spec:
      containers:
        - name: runner
          env:
            - name: RUNNER_DEBUG
              value: "true"
            - name: DOCKER_TLS_CERTDIR
              value: /certs
            - name: DOCKER_HOST
              value: tcp://localhost:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: GH_ORG
              value: sparkfabrik
            - name: RUNNER_LABELS
              value: sparkfabrik,spark-ubuntu-18.04
          # if runner for repo:
          # - name: GH_REPO
          #   value: theRepoName
          envFrom:
            - secretRef:
                name: actions-runner
          image: quay.io/evryfs/github-actions-runner:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - /remove_runner.sh
          resources: {}
          volumeMounts:
            - mountPath: /certs
              name: docker-certs
            - mountPath: /home/runner/.m2
              name: mvn-repo
            - name: sharedv
              mountPath: /home/runner/_work
        - name: docker
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          image: docker:stable-dind
          imagePullPolicy: Always
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-storage
            - mountPath: /certs
              name: docker-certs
            - name: sharedv
              mountPath: /home/runner/_work
      volumes:
        - emptyDir: {}
          name: mvn-repo
        - emptyDir: {}
          name: docker-storage
        - emptyDir: {}
          name: docker-certs
        - name: sharedv
          emptyDir: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - gitlab-ci-build
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - gitlab-ci-build
```

**Comment by andypanix** [comment]
I'm suspecting it's a resource problem. 

Let's me try assigning a minimum of resources request to the runner and let's see if I can reproduce again the error.

**Comment by davidkarlsen** [comment]
```
Exec lifecycle hook ([/bin/bash -c /remove_runner.sh]) for Container "runner" in Pod "runner-pool-pod-s6qkn_saas-github(742ecdfe-e213-11ea-8e34-42010a8400d1)" failed - error: command '/bin/bash -c /remove_runner.sh' exited with 137: , message: "\n# Runner removal\n\n"
```
is the problem to solve.
Is the token still valid? Does it have sufficient rights?

**Comment by andypanix** [comment]
> ```
> Exec lifecycle hook ([/bin/bash -c /remove_runner.sh]) for Container "runner" in Pod "runner-pool-pod-s6qkn_saas-github(742ecdfe-e213-11ea-8e34-42010a8400d1)" failed - error: command '/bin/bash -c /remove_runner.sh' exited with 137: , message: "\n# Runner removal\n\n"
> ```
> 
> is the problem to solve.
> Is the token still valid? Does it have sufficient rights? Is the token key named `GH_TOKEN` https://github.com/evryfs/github-actions-runner/blob/master/remove_runner.sh#L14 ?

Yes, the token is ok, and still valid.

Confirming that it doesn't seem to be a token related problem is that most runners are terminated without errors.

Monitoring memory usage of runner pods, I've seen that some of them are using more then 2600Mi or ram. I've added a resource request in runner manifest as this:

```
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
```

and a preliminary test seems to confirm that the problem is solved. The scale up / down of runner pods is ok and they are cleanly unregistered (and no more FailedPreStopHook  warnings in k8s events).

But when the workflow's queue is done and the runners scale back to 1 in idle state, the currentpoolsize is still to a negative value:

```
NAME                                            READY   STATUS    RESTARTS   AGE
github-actions-runner-operator-d54d7bff-842hj   1/1     Running   0          67m
runner-pool-pod-vzfx6                           2/2     Running   0          22m
NAME          CURRENTPOOLSIZE
runner-pool   -19
```

Anyway, this seems not to be a problem, since when scaling up again, the CURRENTPOOLSIZE value is fine:

```
NAME                                            READY   STATUS    RESTARTS   AGE
github-actions-runner-operator-d54d7bff-842hj   1/1     Running   0          72m
runner-pool-pod-dtw9n                           2/2     Running   0          2m58s
runner-pool-pod-lqpqg                           2/2     Running   0          4m58s
runner-pool-pod-n547m                           2/2     Running   0          57s
runner-pool-pod-nzm7w                           2/2     Running   0          3m58s
runner-pool-pod-smqrs                           2/2     Running   0          5m59s
runner-pool-pod-vb4hc                           2/2     Running   0          117s
runner-pool-pod-vzfx6                           2/2     Running   0          28m
NAME          CURRENTPOOLSIZE
runner-pool   7
```

But when scaling down, the CURRENTPOOLSIZE value is still incorrect:

```
NAME                                            READY   STATUS        RESTARTS   AGE
github-actions-runner-operator-d54d7bff-842hj   1/1     Running       0          76m
runner-pool-pod-dtw9n                           2/2     Running       0          7m10s
runner-pool-pod-lbbmk                           2/2     Running       0          4m9s
runner-pool-pod-lqpqg                           2/2     Running       0          9m10s
runner-pool-pod-n547m                           0/2     Terminating   0          5m9s
runner-pool-pod-nzm7w                           0/2     Terminating   0          8m10s
runner-pool-pod-vzfx6                           2/2     Running       0          32m
NAME          CURRENTPOOLSIZE
runner-pool   -14
```
